Repository astrocamp/17th-WorkNet, pull requests merged in 2024-08, with the labels that each got.

#10 docs: add static files to ignore
  package.json
  src/styles/styles.css
  static/style/style.css
Labels: documentation

#9 refactor:remove duplicate django_extensions
  core/settings.py
Labels: bug

#31 issues/4 新增職缺CRUD/將core更改成config/創建了apps/軟刪除功能
  .env.example
  README.md
  apps/jobs/__init__.py
  apps/jobs/admin.py
  apps/jobs/apps.py
  apps/jobs/forms/__init__.py
  apps/jobs/forms/form.py
  apps/jobs/migrations/0001_initial.py
  apps/jobs/migrations/__init__.py
  apps/jobs/models.py
  apps/jobs/templates/jobs/edit.html
  apps/jobs/templates/jobs/index.html
  apps/jobs/templates/jobs/new.html
  apps/jobs/templates/jobs/show.html
  apps/jobs/tests.py
  apps/jobs/urls.py
  apps/jobs/views.py
  apps/users/forms/users_form.py
  apps/users/models.py
  apps/users/templates/users/home.html
  apps/users/urls.py
  apps/users/views.py
  config/settings.py
  config/urls.py
  lib/models/soft_delete.py
  poetry.lock
  pyproject.toml
  templates/layouts/base.html
Labels: bug, enhancement, company, back end
