Repository astrocamp/17th-WorkNet, pull requests merged in 2024-09, with the labels that each got.

#49 issues/48 會員系統_登入移除重複頁面 & 增加icon
  .env.example
  apps/users/forms/form.py
  apps/users/migrations/0002_userinfo.py
  apps/users/migrations/0003_alter_userinfo_birth_alter_userinfo_updated_at.py
  apps/users/migrations/0004_alter_userinfo_location_alter_userinfo_nickname_and_more.py
  apps/users/templates/users/sign_in.html
  templates/layouts/base.html
Labels: front end

#132 issues/103 新增404 and 403的頁面
  .gitignore
  apps/jobs/views.py
  apps/users/views.py
  config/settings.py
  static/imgs/404_background.jpg
  templates/403.html
  templates/404.html
Labels: front end, back end

#155 issues/151 切版_首頁
  apps/users/templates/users/home.html
  static/imgs/banner.jpg
  static/imgs/icon_like.png
  static/imgs/icon_location.png
  static/imgs/icon_search.png
  static/imgs/icon_star.png
  tailwind.config.js
  templates/shared/navbar.html
Labels: front end, 必要功能

#143 issues/106 公司方收到求職方履歷
  apps/companies/templates/companies/applications.html
  apps/companies/urls.py
  apps/companies/views.py
  apps/users/views.py
  lib/utils/models/decorators.py
  templates/shared/navbar.html
Labels: 必要功能

#190 issues/188 修復_履歷未選擇時會報錯
  apps/users/views.py
Labels: 修改

#166 issues/95 修復_第三方導回到會員資訊問題&取消會錯誤的訊息
  apps/users/urls.py
  apps/users/views.py
Labels: 修改

#200 issues/191 修復_可以直接從網址去別人"修改評論"的問題
  apps/posts/rules.py
  apps/posts/views.py
Labels: 修改

#206 issues/203 履歷_刪除檔名前綴字
  apps/resumes/templates/resumes/index.html
Labels: 修改

#207 issues/189 新增分析內容
  apps/analytics/templates/analytics/index.html
  apps/analytics/views.py
  src/scripts/chart.js
Labels: front end, back end

#239 Issues/232 公司資料表單切版
  apps/companies/forms/companies_form.py
  apps/companies/templates/companies/edit.html
  apps/jobs/views.py
  src/styles/styles.css
  tailwind.config.js
Labels: front end

#233 Issues/231 雇主收到履歷後可以傳信給投遞者
  apps/companies/templates/companies/applications.html
Labels: 次要功能

#248 Issues/240 修正_未登入點職缺報錯
  apps/jobs/templates/jobs/index.html
  apps/jobs/views.py
Labels: 修改

#267 Issues/263 首頁卡片樣式修改
  apps/users/templates/users/home.html
Labels: front end, 修改

#276 issues/275 修正_註冊帳號提示
  apps/users/forms/users_form.py
Labels: front end, back end, 修改

#265 issues/264 修正_navbar顯示姓名
  apps/users/templates/users/home.html
  templates/shared/navbar.html
Labels: front end, 修改

#274 issues/273 切版_公司新增公司資訊
  apps/companies/templates/companies/new.html
Labels: front end, 必要功能, 修改

#278 Issues/270 登入和註冊切版
  apps/users/templates/users/register.html
  apps/users/templates/users/sign_in.html
  templates/shared/navbar.html
Labels: front end

#290 issues/286 修正_職缺的new edit套用 company的樣式
  apps/jobs/forms/jobs_form.py
  apps/jobs/templates/jobs/edit.html
  apps/jobs/templates/jobs/new.html
Labels: 修改

#301 Issues/300 新增banner高度和按鈕動作
  apps/resumes/views.py
  apps/users/templates/users/home.html
Labels: front end, 修改

#303 Issues/302 修復平板/行動版navbur問題
  templates/shared/navbar.html
Labels: bug

#313 issues/312 修正_履歷上傳提示
  apps/users/templates/users/apply.html
Labels: front end, 修改

#297 Issues/247 公司__增加分數 ( model & 畫面 )
  apps/companies/migrations/0007_company_score.py
  apps/companies/models.py
  apps/companies/templates/companies/index.html
  apps/companies/templates/companies/show.html
  apps/companies/views.py
  apps/posts/apps.py
  apps/posts/signals.py
  apps/users/templates/users/home.html
  apps/users/views.py
Labels: 次要功能

#317 issues/316 修正_收藏按鈕顯示
  apps/users/templates/users/favorites.html
Labels: front end, 修改

#262 issues/223 串接_Google Maps API
  .gitignore
  apps/companies/migrations/0007_company_latitude_company_longitude.py
  apps/companies/models.py
  apps/companies/templates/companies/show.html
  apps/companies/views.py
  config/settings.py
  lib/utils/models/defined.py
  static/scripts/map.js
  tailwind.config.js
  templates/layouts/base.html
Labels: company, front end, back end, 次要功能

#315 issues/314 修正_收藏按鈕顯示
  apps/users/templates/users/favorite_company.html
Labels: front end, 修改

#311 issuse/310 修正_調整取消上傳的按鈕顏色
  src/scripts/alert.js
  tailwind.config.js
Labels: front end, 修改

#330 issues/325 評論列表切版
  apps/companies/migrations/0007_company_score.py
  apps/posts/signals.py
  apps/posts/templates/posts/index.html
Labels: front end

#284 issues/283 修正_應徵紀錄可以取消應徵
  apps/resumes/templates/resumes/job.html
  apps/resumes/urls.py
  apps/resumes/views.py
Labels: 必要功能

#355 Issues/354 修正評論的URL路徑
  apps/companies/migrations/0008_company_latitude_company_longitude.py
  apps/companies/models.py
  apps/companies/views.py
  apps/posts/templates/posts/index.html
  apps/users/context_processors.py
  apps/users/views.py
  lib/utils/models/defined.py
  static/scripts/map.js
  templates/shared/notify.html
Labels: 修改

#337 Issues/318 職缺收藏&喜愛的公司_切版
  apps/users/templates/users/favorite_company.html
  apps/users/templates/users/favorites.html
  apps/users/views.py
Labels: front end

#349 Issues/338 修改_職缺列表/詳細
  apps/jobs/templates/jobs/index.html
  apps/jobs/templates/jobs/show.html
  src/scripts/fontawesome.js
  src/styles/styles.css
  tailwind.config.js
Labels: 修改

#363 issues/362 修正_公司信箱可以點選並發送郵件
  apps/companies/templates/companies/show.html
  apps/resumes/templates/resumes/upload.html
  apps/resumes/views.py
Labels: front end, 修改

#382 issues/371 修正_職缺列表
  apps/companies/templates/companies/index.html
  apps/companies/templates/companies/show.html
  apps/jobs/templates/jobs/index.html
  apps/posts/templates/posts/index.html
  apps/users/templates/users/home.html
Labels: 修改

#392 issues/320 修正_footer位置
  apps/companies/templates/companies/edit.html
  apps/companies/templates/companies/index.html
  apps/companies/templates/companies/new.html
  apps/companies/templates/companies/show.html
  apps/jobs/templates/jobs/edit.html
  apps/jobs/templates/jobs/index.html
  apps/jobs/templates/jobs/new.html
  apps/payments/templates/payments/checkout.html
  apps/payments/templates/payments/fail.html
  apps/payments/templates/payments/success.html
  apps/posts/forms/posts_form.py
  apps/posts/templates/posts/edit.html
  apps/posts/templates/posts/new.html
  apps/users/templates/users/info.html
  apps/users/templates/users/password_reset.html
  apps/users/templates/users/password_reset_done.html
  apps/users/templates/users/register.html
  apps/users/templates/users/sign_in.html
  src/styles/styles.css
Labels: 修改

#387 issues/373 修正_個別職缺頁面
  apps/jobs/templates/jobs/show.html
  apps/payments/views.py
Labels: 修改

#375 issues/374 新增首頁hover & 圖片連結
  apps/users/templates/users/home.html
Labels: front end, 修改

#390 issues/388 修正_統一格式 & 下拉式選單hover
  apps/analytics/models.py
  apps/analytics/templates/analytics/index.html
  apps/payments/templates/payments/checkout.html
  config/settings.py
  templates/shared/navbar.html
Labels: front end, 修改

#409 issues/403 修改_評論留言頁
  apps/posts/templates/posts/comment.html
  apps/posts/templates/posts/like.html
  apps/posts/templates/posts/show.html
Labels: front end, 修改

#414 issues/413 新增分析註解
  apps/companies/forms/companies_form.py
  apps/users/views.py
  src/scripts/chart.js
Labels: front end

#416 issues/411 左側主選單hover效果
  templates/shared/navbar.html
Labels: 修改

#418 issues/417 修正_職缺標題block
  apps/jobs/templates/jobs/index.html
Labels: front end, 修改

#426 issues/425 修正_分析圖表註解
  src/scripts/chart.js
Labels: front end, 修改

#429 issues/427 修正_新增留言的間距問題
  apps/posts/templates/posts/show.html
Labels: front end, 修改

#436 issues/435 修改_公司詳細樣式
  apps/companies/templates/companies/show.html
Labels: 修改

#440 issues/439 修改鈴鐺在PC版的問題
  templates/shared/navbar.html
Labels: 修改

#446 issues/445 新增公司詳細有收藏按鈕
  apps/companies/templates/companies/show.html
Labels: 修改

#449 issues/448 新增makefile指令
  makefile
Labels: 修改

#455 Issues/452 修改_公司詳細收藏按鈕重整問題
  apps/companies/templates/companies/show.html
  apps/companies/views.py
Labels: 修改

#457 issues/456 移除職缺詳細的mailto
  apps/jobs/templates/jobs/show.html
Labels: 修改

#465 issues/464 修正_分析圖表數字移除
  apps/jobs/views.py
  src/scripts/chart.js
Labels: front end, 修改
